---
name: Build Radiant Commons Veil Container
on:
  # Build on merge into main
  push:
    branches:
      - main

  # Also support ad-hoc and per-repo calls to trigger builds.
  workflow_call:
  workflow_dispatch:
  repository_dispatch:

  # Build on PRs for testing
  pull_request:
jobs:
  deploy-to-ovh:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/radiantcommons/veil
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          file: ci/containerfiles/Containerfile-veil
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_URL=https://dex.penumbra.zone

      - name: Deploy to Kubernetes
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.K8S_HOST }}
          username: ${{ secrets.K8S_USER }}
          key: ${{ secrets.K8S_SSH_KEY }}
          script: |
            # Set k3s kubeconfig path for k3s clusters
            export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
            
            # Restart veil-service deployment to pull latest image
            sudo kubectl rollout restart deployment veil-service -n penumbra
            
            # Wait for rollout to complete
            sudo kubectl rollout status deployment veil-service -n penumbra --timeout=300s
            
            # Show deployment status
            sudo kubectl get pods -n penumbra -l app=veil-service
