---
name: Build Radiant Commons Veil Container
on:
  # Build on merge into main
  push:
    branches:
      - main

  # Also support ad-hoc and per-repo calls to trigger builds.
  workflow_call:
  workflow_dispatch:
  repository_dispatch:

  # Build on PRs for testing
  pull_request:
jobs:
  veil-radiantcommons:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/radiantcommons/veil
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          file: ci/containerfiles/Containerfile-veil
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_URL=https://dex.penumbra.zone

  veil-testnet:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/radiantcommons/veil

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          file: ci/containerfiles/Containerfile-veil
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ghcr.io/radiantcommons/veil:testnet
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_URL=https://dex-explorer.testnet.plinfra.net
